#!/bin/sh
# Deployapp Script

set -x
set -u

exec 2>&1

echo "Syncing network (ToDo: this is a hack)"

ifconfig >/dev/null 2>&1
sleep 5
ifconfig >/dev/null 2>&1
sleep 2

echo "Getting mac address"

mac=`ifconfig | grep eth0 | egrep -o "([0-9a-fA-F]{2}[:]){5}[0-9a-fA-F]{2}"`
echo "Using mac address $mac"

echo "Checking host registration..."

id=`wget http://192.168.1.1/core/check/$mac -O -`
echo "Check registration: $id" >> /tmp/check

if [ $id = "null" ]
then
    
    echo "Host is unregistered, performing registration"

    register=`wget http://192.168.1.1/core/register/$mac -O -`
    
    echo "Host is idle, waiting for reboot from deployapp"

else
    if echo $id | egrep '^[0-9]+$'
    then
        
        etc="/tmp/deployetc"
        mkdir -p $etc
        
        echo "Host is registered, fetching setup configuration files"
        
        wget http://192.168.1.1/core/fdisk/$id -O - >$etc/fdisk
        cat $etc/fdisk
        
        $deploybin/fdisk $etc/fdisk
        
    else
        
        echo "Grep error: $?"
        echo "Something went wrong"
        
    fi
    
fi


