#!/bin/sh
# Deployapp Script

set -x
set -u

exec 2>&1

echo "Syncing network (ToDo: this is a hack)"

ifconfig >/dev/null 2>&1
sleep 5
ifconfig >/dev/null 2>&1
sleep 2

echo "Getting mac address"

mac=`ifconfig | grep eth0 | egrep -o "([0-9a-fA-F]{2}[:]){5}[0-9a-fA-F]{2}"`
report_ip=`ifconfig | grep -A 1 eth0 | egrep -o "inet addr:(\S+)" | awk -F ':' '{print $2}' | awk -F '.' '{print $4}`

echo "Using mac address $mac, reporting ip $report_ip"

echo "Checking host registration..."

id=`wget http://192.168.1.1/core/check/$mac -O -`
echo "Check registration: $id" >> /tmp/check

if [ $id = "null" ]
then
    
    echo "Host is unregistered, performing registration"
    
    register=`wget http://192.168.1.1/core/register/$mac -O -`
    id=`wget http://192.168.1.1/core/check/$mac -O -`
    wget http://192.168.1.1/core/report/$id/$report_ip -O -
    
    echo "Host is idle, waiting for reboot from deployapp"
    
else
    if echo $id | egrep '^[0-9]+$'
    then
        
        export etc="/tmp/deployetc"
        mkdir -p $etc
        
        echo "Host is registered, fetching setup configuration files"
        
	wget http://192.168.1.1/core/report/$id/$report_ip -O -
        
        # todo todo todo
        echo "ToDo: pause and wait to see if we should actually do any installation"
        
        
        # Create partitions with fdisk
        wget http://192.168.1.1/core/fdisk/$id -O - >$etc/fdisk
        cat $etc/fdisk
        $deploybin/fdisk $etc/fdisk
        
        # Format all partitions to ext2 and mount them under /host
        wget http://192.168.1.1/core/fstab/$id -O - >$etc/mount
        cat $etc/mount
        $deploybin/mount $etc/mount
        
    else
        
        echo "Grep error: $?"
        echo "Something went wrong"
        
    fi
    
fi


