#!/bin/sh
# Deployapp Script

set -x
set -u

exec 2>&1

config=$1

# mountroot=/host/ exported in coordinator

echo "In mount"

# Assumes that the configuration file is ordered by partition number
cat $config | while read LINE
do
    
    echo "Line: $LINE"
    
    # Format <pnumber>:<ptype>:<psize>
    pnumber=`echo $LINE | awk -F ':' '{print $1}'`
    ptype=`echo $LINE | awk -F ':' '{print $2}'`
    psize=`echo $LINE | awk -F ':' '{print $3}'`
    pmount=`echo $LINE | awk -F ':' '{print $4}'`
    
    if [ $ptype -eq 0 ]
    then
        echo "Won't format and partition extended"
        continue
    fi
    
    partitiondev=/dev/sda${pnumber}
    mountpoint=${mountroot}${pmount}
    
    echo "Mounting partition ${partitiondev} to ${mountpoint}"
    
    mkfs.ext2 $partitiondev
    sudo mkdir -p $mountpoint
    sudo mount -t ext2 $partitiondev $mountpoint
    
done

echo "finished mounting process"
