#!/bin/sh

echo "Running deploysetup wrapper"

set -x

export deploybin=/etc/init.d/deploy

$deploybin/coordinator | tee /tmp/deploylog

echo "Running ssh_load_start"

/etc/init.d/ssh_load_start | tee /tmp/sshlog

echo "Done!"
sleep 2



